baseURL: https://lejlasportfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Lejla Kajevic
theme: Personal Web
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Lejla Kajevic! I am a 24-year old MAM student at LBS.
  blog: {}
  contact:
    address:
      - city: London NW1 4SN
        country: England
        street: 45 Hanover Gate Mansions
        title: Address 
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lkajevic.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (079) 34 519 414 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Lejla Kajevic 2022
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: ####
    social:
      - icon: fa-twitter
        label: Twitter
        url: '#'
      - icon: fa-facebook
        label: Facebook
        url: '#'
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/lejlaakajevic/
      - icon: fa-github
        label: GitHub
        url: https://github.com/lejla24
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/lejla-kajevic/
  image: ''
  name: Lejla Kajevic
  navigation:
    button1:
      - name: About Me
        url: blogs
    button2:
      - name: '#'
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: "#"
        url: '#'
      - name: '#'
        url: '#''
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Aliquam
        url: blogs/risk_return
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: About Me
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: massa libero
    url: blogs
