baseURL: https://lejlasportfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Lejla Kajevic
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Data Analytics Portfolio
    subtitle: |-
      This is a site about me, my professional experience, and my data analytics work.
    title: Hello! My name is Lejla Kajevic. Welcome to my website! 
  blog: {}
  contact:
    address:
      - city: London NW1 4SN
        country: England
        street: 45 Hanover Gate Mansions
        title: Address 
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: lkajevic.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7934 519 414 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Lejla Kajevic 2022
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #
      #
      #
      ## - icon: fa-facebook
      ## label: Facebook
      ###
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/lejlaakajevic/
      - icon: fa-github
        label: GitHub
        url: https://github.com/lejla24
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/lejla-kajevic/
  image: ''
  name: Lejla Kajevic
  navigation:
    ###
    ###
    ###
    #
    #
    #
    links:
      - name: Home
        url: '#'
      - name: About Me 
        url: secondblog
      - name: Data Analytics Portfolio
        url: blogs
      ####
      ###
      #
      ###
    menu: Menu
    subtitle: 
    title: 
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpeg
        subtitle: AUT22 Exercise
        title: Risk Return Analysis
        url: blogs/risk_return
      - image: pic02.jpg
        subtitle: Hawaii
        title: Hawaii
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Jordan
        title: Jordan
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Vancouver Island
        title: Vancouver Island
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: The Rocky Mountains
        title: The Rocky Mountains
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: New York
        title: New York
        url: blogs/ipsum
  two:
    buttonText: Read More
    enable: yes
    subtitle: "I am a 24 year old Canadian-Bosnian, currently studying in the MAM program at London Business School.
      \n  I have over 3 years of experience in public-sector investments and fiscal policy within the Government of Canada and NGO sector. In my spare time, I try to travel as much as I can! \n"
    title: About Me
    url: secondblog