---
categories:  
- ""  
- ""
date: "2021-09-30"
description: Prius prices
image: prius.jpeg
keywords: ""
slug: prius_prices
title: Used Prius Prices
---



<p>A recent article in the UK claimed that <a href="https://www.motoringresearch.com/car-news/your-uber-cab-is-most-likely-to-be-a-toyota-prius-and-why-thats-a-good-thing/">your Uber cab is most likely to be a Toyota Prius</a>.</p>
<p>In this workshop, you will use a data file of prices for used Toyota Prius (collected in June 2018) to describe and analyse the dataset, and use your skills in ‘telling a story with data’.</p>
<p>Your task is to carry out analyses of the relationships between price, mileage, colour, and model year for a selected type of car.</p>
<p>You are expected to use this template to create a report with tables, charts, and analysis that will help us understand what drives the price of a used Prius. For instance, you may find the following questions useful in your analysis:</p>
<ul>
<li>How much do cars cost?</li>
<li>How much do car prices vary my engine size, year, etc?</li>
<li>How are car prices associated with mileage? Age? Colour? Location?</li>
<li>How quickly do new cars depreciate?</li>
<li>How much does it cost to drive a car one extra mile?</li>
</ul>
<div id="summary-statistics" class="section level1">
<h1>Summary statistics</h1>
<pre class="r"><code>prius &lt;- read_csv(here::here(&quot;data&quot;,&quot;toyota_prius_jun18.csv&quot;))

skim(prius)</code></pre>
<table style="width: auto;" class="table table-condensed">
<caption>
<span id="tab:load-prius-data">Table 1: </span>Data summary
</caption>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
prius
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
234
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
7
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
town
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
98
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
region
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
colour
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
year
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2010.54
</td>
<td style="text-align:right;">
3.46
</td>
<td style="text-align:right;">
2001
</td>
<td style="text-align:right;">
2008.00
</td>
<td style="text-align:right;">
2010
</td>
<td style="text-align:right;">
2013.00
</td>
<td style="text-align:right;">
2017
</td>
<td style="text-align:left;">
▁▃▇▅▅
</td>
</tr>
<tr>
<td style="text-align:left;">
engine
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1693.81
</td>
<td style="text-align:right;">
143.51
</td>
<td style="text-align:right;">
1497
</td>
<td style="text-align:right;">
1497.00
</td>
<td style="text-align:right;">
1798
</td>
<td style="text-align:right;">
1798.00
</td>
<td style="text-align:right;">
1798
</td>
<td style="text-align:left;">
▅▁▁▁▇
</td>
</tr>
<tr>
<td style="text-align:left;">
miles
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
103187.92
</td>
<td style="text-align:right;">
58644.97
</td>
<td style="text-align:right;">
3200
</td>
<td style="text-align:right;">
63000.00
</td>
<td style="text-align:right;">
93589
</td>
<td style="text-align:right;">
146812.50
</td>
<td style="text-align:right;">
269000
</td>
<td style="text-align:left;">
▅▇▅▂▁
</td>
</tr>
<tr>
<td style="text-align:left;">
price
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
8075.77
</td>
<td style="text-align:right;">
5003.10
</td>
<td style="text-align:right;">
650
</td>
<td style="text-align:right;">
3764.75
</td>
<td style="text-align:right;">
6450
</td>
<td style="text-align:right;">
11983.75
</td>
<td style="text-align:right;">
20995
</td>
<td style="text-align:left;">
▇▇▆▃▂
</td>
</tr>
</tbody>
</table>
<p>The data frame contains prices of used Toyota Prius in the UK that were gathered in June 2018.</p>
<p><code>town</code>, <code>region</code> and <code>colour</code> are categorical variables, whereas <code>miles</code> and <code>price</code> are numerical variables.</p>
<p><code>year</code> and <code>engine</code> are treated as quantitative variables, but in reality are categorical variables.</p>
<pre class="r"><code>prius &lt;- prius %&gt;% 
  mutate(
    engine = factor(engine),# turn it to a factor
    car_age = 2018- year 
  )

favstats(price ~ year, data=prius)</code></pre>
<pre><code>##    year   min       Q1  median       Q3   max      mean        sd  n missing
## 1  2001   650   650.00   650.0   650.00   650   650.000        NA  1       0
## 2  2002  1300  1300.00  1300.0  1300.00  1300  1300.000        NA  1       0
## 3  2004  1200  1781.25  2082.5  2641.25  3995  2340.000 1182.4198  4       0
## 4  2005  1595  2240.00  2550.0  3480.00  4999  2845.929  932.7006 14       0
## 5  2006  1200  2175.00  2697.5  3248.75  5499  2886.125 1298.3677  8       0
## 6  2007   750  1700.00  2850.0  3995.00  4995  2869.692 1350.1192 13       0
## 7  2008  2000  2492.50  3495.0  4847.00  6295  3766.407 1383.2099 27       0
## 8  2009  2200  3700.00  5195.0  6336.25  9980  5130.588 1812.9466 34       0
## 9  2010  3495  5957.50  5990.0  6996.00  8990  6354.179 1199.6136 28       0
## 10 2011  5500  7150.00  8750.0  9990.00 11495  8588.462 1735.3511 13       0
## 11 2012  7995  9149.75  9480.0 10262.50 12990  9861.500 1426.7179 12       0
## 12 2013 10400 10400.00 11600.0 12392.50 15990 11740.000 1483.5147 23       0
## 13 2014 10795 11921.25 12640.0 13450.00 15500 12757.500 1322.9567 14       0
## 14 2015  9600 12500.00 12950.0 13990.00 17899 12999.760 1737.0034 25       0
## 15 2016 14995 15995.00 16995.0 17995.00 19500 17029.444 1521.6530  9       0
## 16 2017 20295 20995.00 20995.0 20995.00 20995 20907.500  247.4874  8       0</code></pre>
<pre class="r"><code>favstats(price ~ engine, data=prius)</code></pre>
<pre><code>##   engine  min   Q1 median    Q3   max      mean       sd   n missing
## 1   1497  650 2250   3190  4255 10750  3426.852 1726.238  81       0
## 2   1798 2095 6450  10400 12991 20995 10536.961 4380.304 153       0</code></pre>
<pre class="r"><code>favstats(price ~ colour, data=prius)</code></pre>
<pre><code>##   colour  min      Q1 median       Q3   max      mean       sd  n missing
## 1  black  650 4127.50 7800.0 12985.00 17995  8337.966 4610.983 59       0
## 2   blue  750 3547.50 5499.0  7775.00 17899  6036.871 3862.309 31       0
## 3   grey 1595 2500.00 4995.0 10500.00 18590  7188.240 5516.924 25       0
## 4    red 2900 5195.00 5195.0  8250.00 13900  6902.933 3409.896 15       0
## 5 silver 1200 3493.75 5872.5 10405.00 19500  7174.018 4475.657 56       0
## 6  white 1700 5990.00 9795.0 13062.25 20995 10951.083 5725.897 48       0</code></pre>
</div>
<div id="manual-calculations-of-confidence-intervals-for-2010-and-2011-mean-prices" class="section level1">
<h1>‘Manual’ calculations of confidence intervals for 2010 and 2011 mean prices</h1>
<p>Note that the average value for a 2010 model is 6354, whereas a 2011 model goes on average for 8588.</p>
<pre class="r"><code># Calculate critical values for the t-distribution for a cumulative of 0.975, i.e., leaving 2.5% on one side

#For 2010 cars, since we have n=28 observations, we have 28-1 = 27 degrees of freedom
qt(0.975, 27)</code></pre>
<pre><code>## [1] 2.051831</code></pre>
<pre class="r"><code>#For 2011 cars, since we have n=13 observations, we have 13-1 = 12 degrees of freedom
qt(0.975, 12)</code></pre>
<pre><code>## [1] 2.178813</code></pre>
<p>Lets look at the relationship between price of a prius and miles driven.</p>
<pre class="r"><code># plot scatter plot and add the best straight line
ggplot(prius, aes(x=miles, y = price))+
  geom_point()+
  theme_bw()+
  geom_smooth(method=&quot;lm&quot;, se=FALSE)+
  NULL</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/blogs/prius_prices_files/figure-html/price_miles_scatter-1.png" width="672" /></p>
</div>
<div id="linear-regression-model" class="section level1">
<h1>Linear Regression Model</h1>
<pre class="r"><code># run linear regression, lm model
model1 &lt;- lm(price ~ miles, data = prius)

# get regression output table
model1 %&gt;% 
  get_regression_table()</code></pre>
<pre><code>## # A tibble: 2 × 7
##   term       estimate std_error statistic p_value  lower_ci  upper_ci
##   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 intercept 14734.      435.         33.9       0 13878.    15590.   
## 2 miles        -0.065     0.004     -17.6       0    -0.072    -0.057</code></pre>
<pre class="r"><code># get R Square
model1 %&gt;% 
  get_regression_summaries()</code></pre>
<pre><code>## # A tibble: 1 × 9
##   r_squared adj_r_squared       mse  rmse sigma statistic p_value    df  nobs
##       &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.572          0.57 10665548. 3266. 3280.      310.       0     1   234</code></pre>
<pre class="r"><code># plot residuals
autoplot(model1) +
  theme_bw()</code></pre>
<p><img src="/blogs/prius_prices_files/figure-html/lm_models-1.png" width="672" /></p>
<pre class="r"><code>#add engine size, as a factor
model2 &lt;- lm(price ~ miles + engine, data = prius)

# get regression output table
model2 %&gt;% 
  get_regression_table()</code></pre>
<pre><code>## # A tibble: 3 × 7
##   term         estimate std_error statistic p_value lower_ci  upper_ci
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 intercept    10078.     491.         20.5       0 9111.    11045.   
## 2 miles           -0.05     0.003     -16.5       0   -0.056    -0.044
## 3 engine: 1798  4795.     372.         12.9       0 4062.     5529.</code></pre>
<pre class="r"><code># get R Square
model2 %&gt;% 
  get_regression_summaries()</code></pre>
<pre><code>## # A tibble: 1 × 9
##   r_squared adj_r_squared      mse  rmse sigma statistic p_value    df  nobs
##       &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.751         0.749 6204126. 2491. 2507.      349.       0     2   234</code></pre>
<pre class="r"><code># plot residuals
autoplot(model2) + 
  theme_bw()</code></pre>
<p><img src="/blogs/prius_prices_files/figure-html/lm_models-2.png" width="672" /></p>
<pre class="r"><code>#add car age
model3 &lt;- lm(price ~ miles + engine + car_age, data = prius)

# get regression output table
model3 %&gt;% 
  get_regression_table()</code></pre>
<pre><code>## # A tibble: 4 × 7
##   term          estimate std_error statistic p_value  lower_ci  upper_ci
##   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 intercept    17630.      491.        35.9    0     16662.    18599.   
## 2 miles           -0.027     0.002    -12.2    0        -0.031    -0.022
## 3 engine: 1798   744.      309.         2.40   0.017   134.     1354.   
## 4 car_age       -976.       50.1      -19.5    0     -1074.     -877.</code></pre>
<pre class="r"><code># get R Square
model3 %&gt;% 
  get_regression_summaries()</code></pre>
<pre><code>## # A tibble: 1 × 9
##   r_squared adj_r_squared      mse  rmse sigma statistic p_value    df  nobs
##       &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.906         0.905 2340926. 1530. 1543.      740.       0     3   234</code></pre>
<pre class="r"><code># plot residuals
autoplot(model3) + theme_bw()</code></pre>
<p><img src="/blogs/prius_prices_files/figure-html/lm_models-3.png" width="672" /></p>
<pre class="r"><code># ________________________________________________________
#add colour and region
model4 &lt;- lm(price ~ miles + engine + car_age + colour + region, data = prius)

# get regression output table
model4 %&gt;% 
  get_regression_table()</code></pre>
<pre><code>## # A tibble: 33 × 7
##    term               estimate std_error statistic p_value  lower_ci  upper_ci
##    &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1 intercept         17620.     1366.       12.9     0     14926.    20313.   
##  2 miles                -0.026     0.002   -10.9     0        -0.031    -0.021
##  3 engine: 1798        748.      355.        2.11    0.036    47.7    1448.   
##  4 car_age           -1023.       57.4     -17.8     0     -1136.     -910.   
##  5 colour: blue        -13.6     371.       -0.037   0.971  -745.      718.   
##  6 colour: grey        292.      428.        0.681   0.497  -553.     1137.   
##  7 colour: red        -147.      469.       -0.314   0.754 -1072.      777.   
##  8 colour: silver     -333.      302.       -1.10    0.271  -928.      262.   
##  9 colour: white       310.      320.        0.97    0.333  -320.      940.   
## 10 region: Berkshire  -283.     1963.       -0.144   0.886 -4153.     3588.   
## # … with 23 more rows</code></pre>
<pre class="r"><code># get R Square
model4 %&gt;% 
  get_regression_summaries()</code></pre>
<pre><code>## # A tibble: 1 × 9
##   r_squared adj_r_squared      mse  rmse sigma statistic p_value    df  nobs
##       &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.918         0.905 2048593. 1431. 1544.      70.1       0    32   234</code></pre>
<pre class="r"><code># plot residuals
autoplot(model4, which = 1:3) + theme_bw()</code></pre>
<p><img src="/blogs/prius_prices_files/figure-html/lm_models-4.png" width="672" /></p>
<pre class="r"><code># no colours are significant. In addition, most regions are not significant, but let us just 
# mutate a new dummy variable &quot;london&quot; to see if london only has an impact

prius &lt;- prius %&gt;% 
  mutate(london = region==&quot;London&quot;)

#add colour and dummy for london
model5 &lt;- lm(price ~ miles + engine + car_age+ london, data = prius)

# get regression output table
model5 %&gt;% 
  get_regression_table()</code></pre>
<pre><code>## # A tibble: 5 × 7
##   term          estimate std_error statistic p_value  lower_ci  upper_ci
##   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 intercept    18224.      538.        33.8    0     17164.    19285.   
## 2 miles           -0.026     0.002    -12.1    0        -0.031    -0.022
## 3 engine: 1798   799.      306.         2.61   0.01    195.     1403.   
## 4 car_age      -1006.       50.9      -19.8    0     -1106.     -905.   
## 5 londonTRUE    -621.      243.        -2.56   0.011 -1099.     -142.</code></pre>
<pre class="r"><code># get R Square
model5 %&gt;% 
  get_regression_summaries()</code></pre>
<pre><code>## # A tibble: 1 × 9
##   r_squared adj_r_squared      mse  rmse sigma statistic p_value    df  nobs
##       &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.909         0.907 2276002. 1509. 1525.      570.       0     4   234</code></pre>
<pre class="r"><code># plot residuals
autoplot(model5, which = 1:3) + theme_bw()</code></pre>
<p><img src="/blogs/prius_prices_files/figure-html/lm_models-5.png" width="672" /></p>
</div>
